version: '3.7'

services:
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000 --settings=room_api_project.settings.local
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        env_file: .env

